application: zipsite
version: 1
runtime: python
api_version: 1

handlers:
- url: /myadmin/.*|/myadmin
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /sitemap.xml|/sitemap.xsl
  script: sitemap.py
  secure: never
  
- url: .*
  script: zipsite.py
  secure: never

builtins:
- datastore_admin: on

