application: zipsite
version: 1
runtime: python
api_version: 1

handlers:

- url: /sitemap\..*
  script: sitemap.py
  secure: never

- url: /sitemap.xml/Create
  script: sitemap.py
  secure: never
  #login: admin

- url: /deletecache
  script: deletecache.py
  secure: never
  #login: admin
  
- url: .*
  script: zipsite.py
  secure: never
  
